twem-1:
  listen: ec2-52-38-229-54.us-west-2.compute.amazonaws.com:22121
  hash: fnv1a_64
  distribution: ketama
  redis: true
  preconnect: true
  servers:
   - jon-test.zmrvj4.ng.0001.usw2.cache.amazonaws.com:6379:1